    //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComTam_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietHD
    {
        public int MaSP { get; set; }
        public int MaHD { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Product Product { get; set; }
    }
}
