//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComTam_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ChitietHDs = new HashSet<ChitietHD>();
        }
    
        public int MaHD { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TenKh { get; set; }
        public string Diachi { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHD> ChitietHDs { get; set; }

        public static implicit operator HoaDon(int v)
        {
            throw new NotImplementedException();
        }
    }
}
