///------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComTam_Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ChitietHDs = new HashSet<ChitietHD>();
            ImageLink = "~/Content/ImageProducts/Product.png";
        }

        public int IdSP { get; set; }
        [Display(Name = "Tên sản phẩm")]
        public string SPName { get; set; }
        [Display(Name = "Số lượng")]

        public int SoLuong { get; set; }
        public string Size { get; set; }
        [Display(Name = "Hình ảnh")]
        public string ImageLink { get; set; }
        [Display(Name = "Giá")]
        public decimal Gia { get; set; }

        public int IdDM { get; set; }
        public virtual DanhMucSP DanhMucSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHD> ChitietHDs { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}

